# Generated by Django 5.0.6 on 2024-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_image_buycar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='qunatity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
